# Workflow para construir e publicar um site com Jekyll usando GitHub Pages
name: Deploy Jekyll para GitHub Pages

on:
  # Executa em pushes para o branch principal
  push:
    branches: ["main"]

  # Permite execução manual do workflow pela aba Actions
  workflow_dispatch:

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma execução do workflow ao mesmo tempo
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Instalar Dependências Jekyll
        run: |
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          gem install bundler jekyll

      - name: Build com Jekyll
        run: |
          mkdir _site
          cp -r build/Release/templates/* _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
